@HOSTNAME=localhost
@PORT=3000
@ACCESS_JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzEsImVtYWlsIjoiZW1lcnNvbi56YXBhdGFAZ21haWwuY29tIiwiaWF0IjoxNzIyODQyMjIyLCJleHAiOjE3MzgzOTQyMjJ9.LrE2IA2FS7K1iJ71Y6PyqWzwkaZvCffGDxDIjCzfqdk

POST http://{{HOSTNAME}}:{{PORT}}/api/authentication/login
Content-Type: application/json

{
  "email": "emerson.zapata@gmail.com",
  "password": "password"
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/authentication/register
Content-Type: application/json

{
  "email": "david.zapatarivas@gmail.com",
  "username": "david zapata",
  "password": "password",
  "password_confirmation": "password"
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/authentication/confirmation
Content-Type: application/json

{
  "token": "123456"
}


###

POST http://{{HOSTNAME}}:{{PORT}}/api/authentication/request
Content-Type: application/json

{
  "email": "john.doe@gmail.com"
}

###

GET http://{{HOSTNAME}}:{{PORT}}/api/authentication/oauth/google

###

GET http://{{HOSTNAME}}:{{PORT}}/api/authentication/user
Cookie: token={{ACCESS_JWT}}

